name: CI/CD to Render

on:
  push:
    branches:
      - master   # Trigger on every push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d3a2o8jipnbc7399dq00" \
        -H "Authorization: Bearer $RENDER_API_KEY"
